export const dynamic = 'force-dynamic'

import './globals.css'
import type { Metadata } from 'next'
import { Cairo, Inter } from 'next/font/google'
import { Toaster } from 'sonner'
import { ReactQueryProvider } from '@/provider/react-query-provider'
import { cn } from '@/lib/utils'
import { ModalProvider } from '@/provider/modal-provider'
import { headers } from 'next/headers'
import CustomerClientProvider from '@/provider/customer-client-provider'
import { getTourTypes } from '@/lib/operations'
import 'swiper/css'
import 'swiper/css/pagination'
import 'swiper/css/navigation'
import 'swiper/css/scrollbar'
import 'swiper/css/effect-cards'
const cairo = Cairo({
  subsets: ['arabic', 'latin'],
  display: 'swap',
  preload: true,
  style: 'normal',
  weight: ['1000', '200', '300', '400', '500', '600', '700', '800', '900'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const headersList = headers()
  const types = await getTourTypes()
  return (
    <html dir={headersList.get('x-dir') ?? 'rtl'} lang={headersList.get('x-lang') ?? 'ar'} style={{ height: '100%' }}>
      <body className={cn(cairo.className, 'h-full')}>
        <CustomerClientProvider types={types.results ?? []}>
          <ReactQueryProvider>
            <ModalProvider />
            <Toaster position="top-right" expand={true} richColors />
            {children}
          </ReactQueryProvider>
        </CustomerClientProvider>
      </body>
    </html>
  )
}
